// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadBlock returns the embedded CollectionSpec for Block.
func LoadBlock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BlockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Block: %w", err)
	}

	return spec, err
}

// LoadBlockObjects loads Block and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BlockObjects
//	*BlockPrograms
//	*BlockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBlockObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBlock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BlockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BlockSpecs struct {
	BlockProgramSpecs
	BlockMapSpecs
}

// BlockSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BlockProgramSpecs struct {
	BlockConnect *ebpf.ProgramSpec `ebpf:"block_connect"`
}

// BlockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BlockMapSpecs struct {
	BlockedIps *ebpf.MapSpec `ebpf:"blocked_ips"`
}

// BlockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type BlockObjects struct {
	BlockPrograms
	BlockMaps
}

func (o *BlockObjects) Close() error {
	return _BlockClose(
		&o.BlockPrograms,
		&o.BlockMaps,
	)
}

// BlockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type BlockMaps struct {
	BlockedIps *ebpf.Map `ebpf:"blocked_ips"`
}

func (m *BlockMaps) Close() error {
	return _BlockClose(
		m.BlockedIps,
	)
}

// BlockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type BlockPrograms struct {
	BlockConnect *ebpf.Program `ebpf:"block_connect"`
}

func (p *BlockPrograms) Close() error {
	return _BlockClose(
		p.BlockConnect,
	)
}

func _BlockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed block_bpfel.o
var _BlockBytes []byte
